POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh5amluMTIzIiwiaWQiOiI2NWU4YjZjNGM0NjM5MDM3ZTBhYTg5MDAiLCJpYXQiOjE3MDk3NDk5NjV9.SpyTHk6QpoLqjTx8h1g5htoM_vA_lja5RGB6LyAqX9E

{
  "title": "Life is good",
  "author": "Sean Jin",
  "url": "www.google.ca",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh5amluMTIzIiwiaWQiOiI2NWU4YjZjNGM0NjM5MDM3ZTBhYTg5MDAiLCJpYXQiOjE3MDk3NDk5NjV9.SpyTHk6QpoLqjTx8h1g5htoM_vA_lja5RGB6LyAqX9E

{
  "title": "I am okay",
  "author": "Sean Jin",
  "url": "www.facebook.ca",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlc3QiLCJpZCI6IjY1ZThiNmJlYzQ2MzkwMzdlMGFhODhmZSIsImlhdCI6MTcwOTc0OTk5NX0.t5UHUE-kNJw1w4Fcvrm0PfPETNiBWdUXTYNRfObSZiA

{
  "title": "I am sleepy",
  "author": "Nancy Tran",
  "url": "www.facebook.ca",
  "likes": 2
}

###
# this is sean's blog, so nancy cannot delete
DELETE http://localhost:3003/api/blogs/65e8b70bc4639037e0aa890a/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlc3QiLCJpZCI6IjY1ZThiNmJlYzQ2MzkwMzdlMGFhODhmZSIsImlhdCI6MTcwOTc0OTk5NX0.t5UHUE-kNJw1w4Fcvrm0PfPETNiBWdUXTYNRfObSZiA


###
# this is nancy's blog, so nancy can delete it
DELETE http://localhost:3003/api/blogs/65e8b711c4639037e0aa890e/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlc3QiLCJpZCI6IjY1ZThiNmJlYzQ2MzkwMzdlMGFhODhmZSIsImlhdCI6MTcwOTc0OTk5NX0.t5UHUE-kNJw1w4Fcvrm0PfPETNiBWdUXTYNRfObSZiA

###
# this is sean's blog, so he can delete it
DELETE http://localhost:3003/api/blogs/65e8b70bc4639037e0aa890a/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh5amluMTIzIiwiaWQiOiI2NWU4YjZjNGM0NjM5MDM3ZTBhYTg5MDAiLCJpYXQiOjE3MDk3NDk5NjV9.SpyTHk6QpoLqjTx8h1g5htoM_vA_lja5RGB6LyAqX9E
